FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD NewMessanger.jar /opt/NewMessanger/
EXPOSE 8080
WORKDIR /opt/NewMessanger/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "NewMessanger.jar"]
